name: Say Something

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        default: 'mooooooooooooooooooooooooooo!'
        required: false
      eyes:
        description: 'Type of eyes'
        default: 'crazy'
        required: false
      tongue:
        description: 'Type of tongue'
        default: 'in'
        required: false

jobs:

  says:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Says something clever
      run: npm run says -- ${{ github.event.inputs.message }} ${{github.event.inputs.eyes}} ${{github.event.inputs.tongue}}
    - name: Update README
      run: |
        git config user.name ${{ secrets.USERNAME }}
        git config user.email ${{ secrets.USER_EMAIL }}
        git add README.md
        git commit -m "Updated README with new CowSay"
        git push origin master
