name: Some Cron

on:
  schedule:
    - cron: "* * * * *"
      
jobs:

  complain:

    runs-on: ubuntu-latest

    steps:
    - name: complain
      run: echo "Errors, It never ENDS!!!!!! prayForMe"
