name: Waiting

on:
  schedule:
    - cron: "0 12-21 * * 1-5"
      
jobs:

  complain:

    runs-on: ubuntu-latest

    steps:
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - name: Thinking while waits
      run: npm run think -- -d disapprove spike
